ansible_host: '192.168.222.101'
interfaces:
  FastEthernet0/0:
    ip_address: '192.168.0.101 255.255.255.0'
    description: 'WAN CONNECTION'
    speed: '100'
    duplex: 'full'
  FastEthernet0/1:
    ip_address: '192.168.0.102 255.255.255.0'
    description: 'SERVER CONNECTION'
    speed: '100'
    duplex: 'full'
  FastEthernet0/2:
    ip_address: '192.168.0.103 255.255.255.0'
    description: 'LAN CONNECTION'
    speed: '10'
    duplex: 'half'
static_routes:
  - '0.0.0.0 0.0.0.0 192.168.0.103'
  - '1.1.1.1 0.0.0.0 10.0.0.1'
eigrp:
  AS: 1
  eigrp_nets:
    - 192.168.0.0 0.0.0.255
    - 10.0.0.0 0.0.0.255
    - 172.16.0.0 0.0.255.255